//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostel_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_in
    {
        public long IdCheck_in { get; set; }
        public int Booking_idBooking { get; set; }
        public string Resident_passport { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Resident Resident { get; set; }
    }
}
